### ISSUE TITLE
discogs: python3-discogs-client version should be >= 2.3.15

### ISSUE THREAD

**Issue by firu82** [sentriz/betanin#109]
Hello plugin DiOrg doesn't work in Docker, you can fix it. 

Thank you

exellent work

**Comment by sentriz** [comment]
thanks. should be working now. if you want to try it. build the image from source. eg compose

```diff
- image: sentriz/betain
+ build: path/to/this/repo
```

**Comment by firu82** [comment]
thanks you !

for the work !
