### ISSUE TITLE
ffmpeg aac

### ISSUE THREAD

**Issue by firu82** [sentriz/betanin#110]
Hello the Convert AAC plugin It works but it doesn't convert anything in Docker This function is available ffmpeg in the container? 

Thank you

**Comment by firu82** [comment]
the ffmpeg inside of the docker compose not support  AAC-LC encoders (aac, libfdk_aac
to mp4 music files

**Comment by sentriz** [comment]
can you give an example ffmpeg command which fails?

**Comment by firu82** [comment]
![ffmpegnoaac](https://github.com/sentriz/betanin/assets/26322641/5f2c9d16-b4f7-414a-baed-3a2f297d10c5)

the ffmpeg build in the container not have the aac encoder libfdk_aac

the commands work fine but no convert filies missin encoder

**Comment by sentriz** [comment]
ffmpeg comes with 3 different AAC encoders seemingly. but libfdk is the proprietary one. do you have an example of a command which fails?

like some ffmpeg -i in.mp4 out.aac

**Comment by sentriz** [comment]
ok glad you got it working. maybe then a good-enough solution is for you to run the container with volume

```
  path/to/custom/ffmpeg:/usr/local/bin/ffmpeg
```

?

or else a custom docker image to overwrite

```
FROM sentriz/betanin
RUN <install custom ffmpeg>
```

because i'm not sure i want to have a custom ffmpeg with --non-free for everyone. hope this makes sense! thanks

**Comment by firu82** [comment]
Ok thanks I'm going to dig
