### ISSUE TITLE
Add ability to skip/remove item in queue

### ISSUE THREAD

**Issue by rosxz** [sentriz/betanin#112]
An album I downloaded and automatically imported got stuck on import:
```
[betanin] retrying... (there are 0 items in the queue)
[betanin] starting cli program
/transcodes/a0d0bfe5799c9fb27e388a849cd7fd8acd0cba11 (V0)
/transcodes/a0d0bfe5799c9fb27e388a849cd7fd8acd0cba11 (V0)/CD 1 - Beatmania & Beatmania IIDX
/transcodes/a0d0bfe5799c9fb27e388a849cd7fd8acd0cba11 (V0)/CD 2 - Dance Dance Revolution
/transcodes/a0d0bfe5799c9fb27e388a849cd7fd8acd0cba11 (V0)/CD 3 - Pop'n Music
/transcodes/a0d0bfe5799c9fb27e388a849cd7fd8acd0cba11 (V0)/CD 4 - Guitar Freaks Drum Mania
/transcodes/a0d0bfe5799c9fb27e388a849cd7fd8acd0cba11 (V0)/CD 5 - Another Series (188 items)

Correcting tags from:
    BEMANI BEST for the 10th anniversary
To:
    BEMANI BEST for the 10th anniversary
URL:
    https://musicbrainz.org/release/25306d2c-b51f-4858-98b8-d9c70649f527
(Similarity: 50.5%)
 (...)
```
I assume the import failed due to the sheer number of tracks on the album, but I'm not sure.
In any case, being able to remove the item from the queue would be nice.

**Comment by knuurr** [comment]
There's something to it. I also have his problem where betanin out of nowhere started to try to import same album over and over again,

If I hit Skip or Abort, it tries again. It's always on "needs input" or "Processing"

I'm not sure when this happened (I had no issue until very recently). Could ungraceful shutdown affect it? Can this be manually dealth with?

Stop and restart of container does not help. I could always nuke data folder for betanin, but maybe there is other possibility.

**Comment by sentriz** [comment]
can you try `sqlite3 path/to/betanin.db "update torrents set status = 'completed' where id=X" `

**Comment by sentriz** [comment]
X can be found in the web UI by clicking the arrow on a row

**Comment by knuurr** [comment]
Nvm for me it was one of plugins balooning memory and crashing import. Together with `hook` plugin (I had it run on import) it resulted in importing procedure never marked as completed - even though files were in beet database, betanin didn't have chance to mark it within it's databse.

**Comment by rosxz** [comment]
Sorry for being AWOL I haven't experienced the issue again and my dumb ass didn't try to test it further at the time (I was kind of busy anyway), I'll close the issue, thanks for the attention.
