### ISSUE TITLE
Update beets to V1.61 (git)

### ISSUE THREAD

**Issue by andrewjmetzger** [sentriz/betanin#117]
Hi sentriz, 

Beets V1.6.0 has not been updated since November of 2021. When you pull the release zip to setup betanin, beets is stuck on the old V1.6.0 version.

I'd like to propose a simple change to [requirements-docker.txt](requirements-docker.txt). 

Since [beets' maintainers suggest](https://github.com/beetbox/beets/pull/4705) this git-based install,
```
pip install git+https://github.com/beetbox/beets.git
```
... should the betanin requirements file do the same? For example:
```
beets @ git+https://github.com/beetbox/beets.git
```

I am happy to fork and PR, but wanted to open this discussion first. 

Thanks for making betanin so awesome, and happy new year! :)  
Andrew

**Comment by sentriz** [comment]
hm not sure i understand. betanin is already using beets @ master which can be seen here https://github.com/sentriz/betanin/blob/master/requirements-docker.txt#L1

**Comment by andrewjmetzger** [comment]
Hmm... Before I did a manual update, it was on beets V1.6.0. Let me double-check.

**Comment by andrewjmetzger** [comment]
Aha, sorry! I had to pull the docker image again. :(
All good now. :)
```
/src # beet --version
beets version 1.6.1
```
