### ISSUE TITLE
Trouble adidng "beets-alternative" / external plugins into image on build

### ISSUE THREAD

**Issue by knuurr** [sentriz/betanin#118]
Hi,

I wanted to incorporate a `beets-alternatives` plugin into Betanin image.

I already have refined config I tested with dockerized version of Beets (just Beets, not Betanin) where I basically tested a pipeline I wanted to create which involves creating a mirror of my library but in MP3 format for usage with external players, such as my phone.

So I think it makes sense for me to instead keep a separate from Betanin instance of Beets, just add necessary packages to this image, so whenever I use Betanin to digets anything form staging folder for my music:

- I use Betanin web UI to point to new folder to integrate it with library - or use one of torrent clients' integration
- with my current config, after Betanin sucessfuly adds new file into library, I can use something like `hook` plugin to call `beets-alternatives`' `beet alt update` command as post-import event, so anything new is also mirrored 
- So ideally, as end goal, anything imported via Betanin is given additional handling
- Had I ever had a need of any non-standard action - say `beet update` to reflect out of band changes - I would always use interactive session from within Betanin container. This allows me to avoid 2 different containers on the system.

To achieve what I'm saying I quickly added this part to my docker-compose file to ensure plugins have necessary dependencies and to install `beets-alternatives` plugin:

```yml
build:
# Support for beet-alternatives plugin
 dockerfile_inline: |
   FROM sentriz/betanin:v0.5.6
   RUN pip install beautifulsoup4 requests \
     && pip install --upgrade beets>=1.6.0 beets-alternatives
```

However this doesn;t seem to work. I verified it also on vanilla image of Betanin and tried to perform these steps through interactive shell.

`beet alt` command from plugin is not recognized.

```
/src #  pip install --upgrade beets>=1.6.0 beets-alternatives
WARNING: The directory '/b/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/src # beet version
beets version 1.6.1
Python version 3.11.6
no plugins loaded
/src # beet alt
error: unknown command 'alt'
```

 I also tried doing `su betanin`, and then installation and effects are the same.

```
/src $ pip install --upgrade beets-alternatives
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beets-alternatives in /usr/lib/python3.11/site-packages (0.11.0)
Requirement already satisfied: beets<2.0.0,>=1.6.0 in /usr/lib/python3.11/site-packages (from beets-alternatives) (1.6.1)
Requirement already satisfied: six<2.0.0,>=1.16.0 in /usr/lib/python3.11/site-packages (from beets-alternatives) (1.16.0)
Requirement already satisfied: unidecode>=1.3.6 in /usr/lib/python3.11/site-packages (from beets<2.0.0,>=1.6.0->beets-alternatives) (1.3.7)
Requirement already satisfied: musicbrainzngs>=0.4 in /usr/lib/python3.11/site-packages (from beets<2.0.0,>=1.6.0->beets-alternatives) (0.7.1)
Requirement already satisfied: pyyaml in /usr/lib/python3.11/site-packages (from beets<2.0.0,>=1.6.0->beets-alternatives) (6.0.1)
Requirement already satisfied: mediafile>=0.12.0 in /usr/lib/python3.11/site-packages (from beets<2.0.0,>=1.6.0->beets-alternatives) (0.12.0)
Requirement already satisfied: confuse>=1.5.0 in /usr/lib/python3.11/site-packages (from beets<2.0.0,>=1.6.0->beets-alternatives) (2.0.1)
Requirement already satisfied: munkres>=1.0.0 in /usr/lib/python3.11/site-packages (from beets<2.0.0,>=1.6.0->beets-alternatives) (1.1.4)
Requirement already satisfied: jellyfish in /usr/lib/python3.11/site-packages (from beets<2.0.0,>=1.6.0->beets-alternatives) (1.0.3)
Requirement already satisfied: typing-extensions in /usr/lib/python3.11/site-packages (from beets<2.0.0,>=1.6.0->beets-alternatives) (4.9.0)
Requirement already satisfied: mutagen>=1.46 in /usr/lib/python3.11/site-packages (from mediafile>=0.12.0->beets<2.0.0,>=1.6.0->beets-alternatives) (1.47.0)
/src $ beet alt
error: unknown command 'alt'
```

Calling `beet help` on both ocasions works just fine.

```
/src # beet help
Usage: 
  beet COMMAND [ARGS...]
  beet help COMMAND

Options:
  --format-item=FORMAT_ITEM
                        print with custom format
  --format-album=FORMAT_ALBUM
                        print with custom format
  -l LIBRARY, --library=LIBRARY
  
  ....
```

So - what am I missing here and what's the best way in my use case to bundle these external dependencies with app? 
I believe it must be possible, it's just that I have trouble with ownership of files there.

**Comment by sentriz** [comment]
I think it's possible without changing the image at all

eg in my beets config I have 

```yaml
pluginpath:
  - /b/.config/betanin/plugins/beets-fetchartist/beetsplug
  - /b/.config/betanin/plugins/beets-originquery/beetsplug
```

then I docker Mount those dirs into the container. on the other size of the mount, they're just clones of the plugin repos

**Comment by knuurr** [comment]
> I think it's possible without changing the image at all
> 
> eg in my beets config I have
> 
> ```yaml
> pluginpath:
>   - /b/.config/betanin/plugins/beets-fetchartist/beetsplug
>   - /b/.config/betanin/plugins/beets-originquery/beetsplug
> ```
> 
> then I docker Mount those dirs into the container. on the other size of the mount, they're just clones of the plugin repos

I must say I missed this functionality of pointing out a plugin folder. Actually it's pretty useful in my case.

I really like to have the least amount of statc binding and isolate everything as much as possible, I did a small dirty hack and just fetched plugin contents fdirectly using recenty introduced `dockerfile_inline:` directive for docker-compose

```
    build:
      # Support for beet-alternatives plugin
      dockerfile_inline: |
        FROM sentriz/betanin:v0.5.6
        RUN mkdir -p /opt/plugin/beets-alternatives/beetsplug \
            && cd /opt/plugin/beets-alternatives/beetsplug \
            && wget -O __init__.py https://raw.githubusercontent.com/geigerzaehler/beets-alternatives/main/beetsplug/__init__.py \
            && wget -O alternatives.py https://raw.githubusercontent.com/geigerzaehler/beets-alternatives/main/beetsplug/alternatives.py
```


Just tested it today and it works. I mean, plugin is accessible from inside container

**Comment by sentriz** [comment]
nice one :+1: glad you got it sorted
