### ISSUE TITLE
IDEA: Listen in path for new folder/files to consume

### ISSUE THREAD

**Issue by knuurr** [sentriz/betanin#121]
Although I use inetgration with torrent client via proposed scripts, way more often I need to manually drag and drop folder with my newly ripped music from CDs 😋😋😋 into path which Betanin is bound to.

I wonder if more event driven pattern based on when any new folder with files gets dropped into location is possible - either by native solutions or other hacky means.

I mean currently I just have around 50 new compilations to add, manual picker isn't really convienet for that, and drop-and-forget approach would be really convienient too.

If no plan (or capacity) for native functionality, then does anyone have idea to achieve same functionality but through other means?

**Comment by sentriz** [comment]
hi, not tested at all, but if you have access to a unixy environment, you could try using inotifywait to watch for new directories, then send them to betanin with curl. something like

```bash
while true; do
    dir="$(inotifywait --quiet --event create --format "/path/to/rips/relative/to/betanin/inside/docker/%f" "/path/to/new/rips")"
    sleep 2 # wait for all files inside to be copied

    curl --request POST --data-urlencode "both=$dir" --header "X-API-Key: yourbetaninapikey" "https://betanin/api/torrents"
done
```

**Comment by jee-r** [comment]
I've something similar but running in a docker container :

https://gist.github.com/jee-r/a4a7e30f199beb6dfd552be36b74b24a

**Comment by knuurr** [comment]
@jee-r brilliant solution.

I will be testing it. I just wonder if there are whatsoever no issues with directories and files within them that don't get removed at the end of import process.

Currently tested it on small scale, on one folder, looks fine for now, but just want to know your experience.
