### ISSUE TITLE
Add timeout for imports which need additional input (so rest of queue won't be blocked)

### ISSUE THREAD

**Issue by knuurr** [sentriz/betanin#123]
Let's say there is one album that for any reason (like there is slight mismatch in MusicBrainz and detected version, and it fails % threshold) can't be imported.

I've often had such situation that I attempted import of few albums in row, went away, came back only to find out that the very first album in queue clogged queue. After intervention - confirm or abort - rest very often just imported.

Proposal: Add (configurable) timeout for import - counting from time the need for input arises. 

Betanin could automatically send command such as Abort or other, or just kill import process and mark it in it's databse as failed (here I assume there wouldn't be problems with database, but since `beet` never really started import I think that's not an issue.)

Time interval could be additionaly fetched from config file, 0 could mean disabled, and any value over 0 could be time in seconds to wait for user input.

I don't think I understand Betanin well enought to attempt an implementation (yet), but with some clues how entire process is handled, maybe I could one day work on it.

**Comment by sentriz** [comment]
i think this is solved by #39. can you try set `num_parallel_jobs = x` in config.toml, with x > 1. you may see beets lock error but that could be a nice thing to try fix if you can
