### ISSUE TITLE
[FR] [Docker] Set UID and GID

### ISSUE THREAD

**Issue by edgar-vincent** [sentriz/betanin#23]
Hi!
Would it be possible to set the UID and GID of the Docker container's user?
Thanks!

**Comment by sentriz** [comment]
i'm not tooo familiar with users and groups inside containers. if the dockerfile supported these, how would it differ to running with `docker run --user $UID:$GID` or `user: $UID:$GID` in compose?

**Comment by sentriz** [comment]
merged! please let me know if it broken somehow :)
