### ISSUE TITLE
Mnamer

### ISSUE THREAD

**Issue by dgiffen** [sentriz/betanin#31]
Not really an issue, but have you considered using mnamer instead of/or including filebot. Mnamer  uses way fewer resources and is of this time totally free where as Filebot is a pay only app. Its also pretty accurate and extremely fast. jkwill87/mnamer is the github site

**Comment by sentriz** [comment]
hello. betanin uses [beets.io](https://beets.io) under the hood, not filebot (written in java) whereas betanin and beets are both python - so personally i think they are a nice match together
