### ISSUE TITLE
Beet Config?

### ISSUE THREAD

**Issue by tedtms** [sentriz/betanin#37]
Hey! Sorry, I'm new to this project so I'm not super certain. For Betanin to work, do I have to have beets.io already installed?

When I got to the Settings page in Betanin and then the Beet config page, it says the config.yaml isn't present.

Thanks!

**Comment by sentriz** [comment]
hi! yes betanin is basically a fancy web wrapper for your already setup beets config

if you're using the docker image beets will already be installed, you just need to create a beets.yml file at `./beets/config.yaml`

or if your using the normal python package, it will be a new file like
- linux `~/.config/beets/config.yaml`
- windows `%APPDATA%\beets\config.yaml`
- osx `~/Library/Application Support/beets/config.yaml`


more info is here if you haven't seen it already 
https://beets.readthedocs.io/en/stable/reference/config.html

please re-open if you have any trouble with this. thanks!
