### ISSUE TITLE
Parallel import

### ISSUE THREAD

**Issue by w1ldg00se** [sentriz/betanin#39]
Is there any reason why there's only a single import at a time?

I added a huge bunch of import requests and many of them need manual input. I open the console, mostly 
just press [A]pply or [S]kip and would like to just go to the next import with manual input. But i need to wait for the current import to finish and for the next to detect the album and request my manual input. That means i need to wait around half a minute to 5 minutes until i can proceed with the next import, so i switch to doing something else and often forget to come back.
That's the same issue i had with a bash script that starts the `beet import` for every folder in my music download directory and the only reason why i installed betanin.

Couldn't it just do: hey beets needs manual intervention, so i just start the next import.
And after all imports are processed they are either successfully imported or need manual input.

**Comment by sentriz** [comment]
hey
this is something i've wanted too, but i wasn't sure if two beets subprocesses would freak out if they were running at the same time.
i did some light tested and there didn't seem to be any issues with parallel manual cli imports

however when implementing this with betanin, i went to build the project again, and ran into this:
https://github.com/pyca/cryptography/issues/5771

which was kinda frustrating. i tried 
- downgrading `cryptography` in setup.py deps
- downgrading `apprise` (i think it's what requires `cryptography`)
- `CRYPTOGRAPHY_DONT_BUILD_RUST=1`
- installing `openssl-dev` `libressl-dev` in the alpine image

with no luck

i'd happy a accept a fix for this if you can come up with one

here's the diff I think may do parallel imports

```diff
diff --git a/betanin/config/betanin.py b/betanin/config/betanin.py
index 85d493e..17872f3 100644
--- a/betanin/config/betanin.py
+++ b/betanin/config/betanin.py
@@ -22,6 +22,7 @@ _DEFAULT_CONFIG = {
         },
     },
     "clients": {"api_key": ""},
+    "num_parallel_jobs": 1,
 }
 _NEEDED_CONFIG_PATHS = (
     # (path, ) reason
@@ -85,6 +86,10 @@ def get_api_key():
     return read()["clients"]["api_key"]
 
 
+def get_num_parallel_jobs():
+    return read().get("num_parallel_jobs", 1)
+
+
 def ensure():
     if not _file_exists():
         logger.error(
diff --git a/betanin/jobs/import_torrents.py b/betanin/jobs/import_torrents.py
index 78536af..85602f4 100644
--- a/betanin/jobs/import_torrents.py
+++ b/betanin/jobs/import_torrents.py
@@ -8,6 +8,7 @@ from ptyprocess import PtyProcessUnicode
 from gevent.queue import Queue
 
 # betanin
+import betanin.config.betanin as conf_betanin
 from betanin import events
 from betanin import notifications
 from betanin.models import Line
@@ -130,4 +131,7 @@ def start(flask_app):
         with flask_app.app_context():
             _start()
 
-    return gevent.spawn(with_context)
+    num_parallel_jobs = conf_betanin.get_num_parallel_jobs()
+    return gevent.joinall(
+        gevent.spawn(with_context) for _ in range(num_parallel_jobs)
+    )
```

and a `num_parallel_jobs = 4` for example in the betanin `config.toml`
