### ISSUE TITLE
Web UI runs into timeout on many finished imports / add backend pagination 

### ISSUE THREAD

**Issue by w1ldg00se** [sentriz/betanin#42]
I now have nearly 1600 finished imports (0 active) and the following performance issue appeared:
The route `/api/torrents` isn't very efficient so with this amount of imports it takes just over 5 seconds to finish the request. The web ui has a timeout of 5 seconds (backend.js, line 9) and thus runs into the timeout, so the web ui always just shows `disconnected` and shows none of the finished imports.
Increasing the timeout in backend.js makes everything working again.

So the performance of the route `/api/torrents` should be increased somehow. By default betanin uses pagination with 50 entries per page so maybe it's possible to only return the first 50 entries and load the next 50 entries only on demand when the user visits the next site. ~~Also sorting after the date via code is probably slower than using plain SQL.~~ Edit: Probably not, that's standard flask_sqlalchemy code which should already generate SQL.

And a button which deletes all finished imports would be nice (and a fast fix).

**Comment by sentriz** [comment]
yeah I am very much running into this issue too. backend pagination is something I would definitely like to have

in the meantime you could do something 
```
$ sqlite3 data/betanin.db "delete from lines"
$ sqlite3 data/betanin.db "delete from torrents"
```
