### ISSUE TITLE
Qbittorrent support?

### ISSUE THREAD

**Issue by tandy-1000** [sentriz/betanin#59]
It would be nice to have instructions / support for Qbittorrent

**Comment by sentriz** [comment]
hi! would it be qbittorrent for desktop? mac/linux/windows?
or the web based version / docker?

**Comment by tandy-1000** [comment]
I should have clarified, I use qbittorrent on Linux with the web UI, so I guess that is just qbittorrent.

**Comment by sentriz** [comment]
i just added an example to the readme. just from looking at the docs though so not tested. let me know if it works :+1:

**Comment by tandy-1000** [comment]
thank you! working well :)
