### ISSUE TITLE
Betanin crashes immediately on import

### ISSUE THREAD

**Issue by tedtms** [sentriz/betanin#65]
Hello,

First off, awesome project! I'd love to get it working however I'm having a bit of an issue. Whether triggered by API or by manual import, betanin crashes immediately when a directory is added for import and can only recover by deleting the betanin.db and restarting the daemon. My beet user and betanin user are the same, and the user has permissions to write/edit the directory being imported, so I don't _think_ it's permissions related... Is there a way to enable debug logs for betanin? 

![image](https://user-images.githubusercontent.com/49801453/168951897-98471656-afa2-40bc-8373-498f635c9eab.png)

**System details:**
OS: Proxmox PVE (Ubuntu 20.04 lxc)
CPU: 4 vCPUs
RAM: 512MB (I've tried upping this to 8GB but nothing changes)

**`journalctl` logs:**

```
May 18 03:26:21 beets betanin[18708]: 2022-05-18 03:26:21.431 | INFO     | betanin.jobs.import_torrents:_start:108 - got new torrent
May 18 03:26:21 beets systemd[1]: betanin.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit betanin.service has successfully entered the 'dead' state.
May 18 03:26:21 beets systemd[1]: betanin.service: Consumed 1.784s CPU time.
-- Subject: Resources consumed by unit runtime
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit betanin.service completed and consumed the indicated resources.
```

Thanks!

**Comment by sentriz** [comment]
that's weird. and it looks like it's exiting with code 0?

**Comment by tedtms** [comment]
Yeah it's super strange. I'm assuming that when betanin receives a path to import, it's just executing `beet` as the same user that's running the betanin web server right? Does it execute `beet` using the full executable path?

**Comment by sentriz** [comment]
yep you're right about the $PATH :+1: for some reason if betanin can't find `beet` in your $PATH, an exception is raised but gevent is eating it and not printing for some reason

i just added a commit that will check $PATH first and not crash



> Does it execute beet using the full executable path?

no it just checks $PATH

**Comment by tedtms** [comment]
So, I'm getting a 500 error now on the frontend when opening betanin's web page but the server console output doesn't provide any useful error information. Where can I find whatever log has the $PATH error you added?

Also, it's strange, because `beet` is definitely in my user's $PATH. My system has a user called "beets" that runs both the `betanin` server and has `beet` installed in its ~/.local/bin directory, which is included in $PATH.

**Comment by sentriz** [comment]
hmm i didn't change anything in the most recent commit that would give you a 500. though that can happen if the server can't find the frontend assets 

what happens if you install betanin==0.3.36 ?

**Comment by tedtms** [comment]
> what happens if you install betanin==0.3.36 ?

I get an installation error because betanin requires `importlib-metadata==3.3.0' but somewhere up the dependency chain it also requires `markdown 3.3.6` which in turn requires `importlib-metadata>=4.4.0`. I was able to get past this by downloading the source and changing the requirements in `setup.py` but I feel like that could be the cause of some of my problems.

**Comment by tedtms** [comment]
OK so part of my problem is definitely with $PATH. I had `/home/beets/.local/bin` as part of $PATH in `/etc/environment` and moved it to `~/.profile` which fixed my 500 error. Betanin 0.3.36 is running fine now. And now when I do manual imports, I'm getting the $PATH error in the CLI view instead of betanin just crashing. 

What's confusing to me though is that `beet` is _definitely_ in $PATH. It's in _the same folder as betanin_ and they're both run by the same user. So why can't betanin find it?

**Comment by sentriz** [comment]
hmm that's odd. is `beet` marked as executable?

**Comment by tedtms** [comment]
Indeed.

**Comment by tedtms** [comment]
So, this may not be an actual solution, but I copied the `beet` binary from my beets user's `~/.local/bin dir` to `/usr/bin` and now betanin works. Do you pre-define $PATH somehow in betanin? Or does it use its user's $PATH like normal? The only thing I can think of is that it's not using the user's $PATH but is instead looking at some predefined $PATH that doesn't contain `beet` if you install `beet` as a user instead of globally.

**Comment by sentriz** [comment]
cool that you got it working 👍 betanin uses the $PATH var which comes from the parent process. in this case it's systemd with the beets user it seems? what does systemd set PATH to? 

perhaps you need to move the beet binary to ~beets/.local/bin not ~/.local/bin

**Comment by tedtms** [comment]
That's where it was -- the home directory .local/bin for the beets user. Unless I'm misunderstanding you
