### ISSUE TITLE
GStreamer ReplayGain error

### ISSUE THREAD

**Issue by RodolfoFigueroa** [sentriz/betanin#87]
When using the `replaygain` plugin with the `gstreamer` backend, all imports fail with the error:

```
error: replaygain initialization failed: Failed to load GStreamer: python-gi not found
```

Installing `py-gobject3` and `gst-plugins-good` fixes this.

**Comment by sentriz** [comment]
hi, are you suggesting to add those deps to the docker container? if not docker then betanin doesn't really deal with plugin's deps since the user can just install them normally
